### ISSUE TITLE
Dependencies not available anymore

### ISSUE THREAD

**Issue by KobusPost** [lethexa/lethexa-trackdisplay#1]
When trying to install the bower dependencies it fails on the following package:
    "lethexa-geo"

This is on a separate git server (git@cfg.home.web:/~/base/js/lethexa-geo.git#~1.0.0)

Do you have this package for me? or consider moving it to GitHub to keep this app alive

**Comment by lethexa** [comment]
Fixed dependency and made it public. It should start now.
